=== LapinTade/TPL3/XML/for-lc-2/sf-1.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--  Parameter entities.  -->

<!ENTITY % INTEGER           "(#PCDATA)">
<!ENTITY % INTEGER-A         "CDATA">
<!ENTITY % STRING            "#PCDATA | personrefs | emph">
<!ENTITY % STRING-PLUS       "%STRING; | foreigngroup">
<!ENTITY % STRING-PLUS-PLUS  "%STRING-PLUS; | nonemptyinformation">

<!ENTITY % id.attribute      "id       ID      #REQUIRED">
<!ENTITY % lang.attribute    "xml:lang NMTOKEN 'en'">
<!ENTITY % basic.attributes  "%id.attribute; %lang.attribute;">

<!--  Elements and their attributes.  -->

<!ELEMENT sf-1     (entries,persons)>
<!ELEMENT entries  (book | inproceedings)*>

<!ELEMENT book           ((author | editor),title,publisher,year,month?,
                          (volume | number)?,series?,address?,edition?,
                          translated-by?,note?)>
<!ELEMENT inproceedings  (author,title,booktitle,editor?,organization?,
                          publisher?,year?,month?,volume?,number?,series?,
                          address?,pages?,translated-by?,note?)>
<!ATTLIST book           %basic.attributes;>
<!ATTLIST inproceedings  %basic.attributes;>

<!ELEMENT author         (personrefs)>
<!ELEMENT editor         (personrefs)>
<!ELEMENT personrefs     EMPTY>
<!ELEMENT and-others     EMPTY>
<!ELEMENT translated-by  (personrefs,and-others?)>
<!ATTLIST personrefs     to   IDREFS  #REQUIRED>
<!ATTLIST translated-by  from NMTOKEN #REQUIRED>

<!ELEMENT year   %INTEGER;>
<!ELEMENT month  (jan | feb | mar | apr | may | jun | jul | aug | sep | oct |
                  nov | dec)>
<!ELEMENT jan    EMPTY>
<!ELEMENT feb    EMPTY>
<!ELEMENT mar    EMPTY>
<!ELEMENT apr    EMPTY>
<!ELEMENT may    EMPTY>
<!ELEMENT jun    EMPTY>
<!ELEMENT jul    EMPTY>
<!ELEMENT aug    EMPTY>
<!ELEMENT sep    EMPTY>
<!ELEMENT oct    EMPTY>
<!ELEMENT nov    EMPTY>
<!ELEMENT dec    EMPTY>

<!ELEMENT title      (%STRING-PLUS; | skippable)*>
<!ELEMENT booktitle  (%STRING-PLUS; | skippable)*>
<!ELEMENT emph       (#PCDATA)>
<!ATTLIST emph       bff     (yes | no) "no" 
                     emf     (yes | no) "yes"
                     itf     (yes | no) "no"
                     quotedf (yes | no) "no"
                     scf     (yes | no) "no"
                     sff     (yes | no) "no"
                     slf     (yes | no) "no"
                     ttf     (yes | no) "no">
<!ELEMENT skippable  (#PCDATA)>

<!ELEMENT note                 (%STRING-PLUS-PLUS; | group)*>
<!ELEMENT nonemptyinformation  (group+)>
<!ELEMENT group                (%STRING;)*>
<!ELEMENT foreigngroup         (%STRING;)*>
<!ATTLIST group                %lang.attribute;>
<!ATTLIST foreigngroup         %lang.attribute;>

<!ELEMENT pages          (firstpage,(and-following | lastpage | otherpages)?)>
<!ELEMENT firstpage      %INTEGER;>
<!ELEMENT lastpage       %INTEGER;>
<!ELEMENT otherpages     (pagenumber+)>
<!ELEMENT pagenumber     %INTEGER;>
<!ELEMENT and-following  EMPTY>
<!ELEMENT number         (#PCDATA)>
<!ELEMENT volume         (#PCDATA)>

<!ELEMENT address       (%STRING-PLUS-PLUS;)*>
<!ELEMENT edition       (%STRING-PLUS-PLUS;)*>
<!ELEMENT organization  (%STRING-PLUS-PLUS;)*>
<!ELEMENT publisher     (%STRING-PLUS-PLUS;)*>
<!ELEMENT series        (%STRING-PLUS-PLUS;)*>

<!ELEMENT persons       (personname*)>
<!ELEMENT personname    (first?,middle?,von?,last,junior?,pseudonym-of?)>
<!ELEMENT first         (#PCDATA)>
<!ELEMENT von           (#PCDATA)>
<!ELEMENT middle        (#PCDATA)>
<!ELEMENT last          (#PCDATA)>
<!ELEMENT junior        EMPTY>
<!ELEMENT pseudonym-of  (personrefs,and-others?)>
<!ATTLIST personname    key  ID          #REQUIRED
                        born %INTEGER-A; #IMPLIED
                        dead %INTEGER-A; #IMPLIED>

=== LapinTade/TPL3/XML/for-lc-2/books-1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE sf-1 SYSTEM "sf-1.dtd">

<sf-1>

  <entries>

    <book id="beahm1996" xml:lang="fr">
      <author><personrefs to="beahm"/></author>
      <title>
        Tout sur <foreigngroup xml:lang="en">Stephen King</foreigngroup>
      </title>
      <publisher>Lefrancq</publisher>
      <year>1996</year>
      <translated-by from="en"><personrefs to="corthouts"/></translated-by>
    </book>

    <book id="bachman1982" xml:lang="en">
      <author><personrefs to="bachman"/></author>
      <title><skippable>The </skippable>Running Man</title>
      <publisher>New American Library</publisher>
      <year>1982</year>
      <month><may/></month>
    </book>

    <book id="bisson1995" xml:lang="en">
      <author><personrefs to="bisson"/></author>
      <title>Johnny Mnemonic</title>
      <publisher>Simon &amp; Shuster, Inc.</publisher>
      <year>1995</year>
      <note>
        Based on a short story and screenplay by <personrefs to="gibson"/>
      </note>
    </book>

    <book id="duncan1999" xml:lang="en">
      <author><personrefs to="duncan"/></author>
      <title>I Know What You Did Last Summer</title>
      <publisher>Dell</publisher>
      <year>1999</year>
      <month><jul/></month>
      <note>
        <nonemptyinformation>
          <group xml:lang="en">
            Film adaptation directed by <personrefs to="moritz"/>
          </group>
          <group xml:lang="fr">
            Adapté au cinéma sous le titre :
            <emph quotedf="yes">Souviens-toi, l'été dernier</emph>
          </group>
        </nonemptyinformation>
      </note>
    </book>

    <inproceedings id="egan2001" xml:lang="en">
      <author><personrefs to="egan"/></author>
      <title>Oracle</title>
      <booktitle>
        <skippable>The </skippable>Mammoth Book of Best New SF
      </booktitle>
      <editor><personrefs to="dozois"/></editor>
      <publisher>Robinson</publisher>
      <year>2001</year>
      <volume>14</volume>
      <address>London</address>
      <pages><firstpage>465</firstpage><lastpage>504</lastpage></pages>
    </inproceedings>

    <book id="eschbach1999" xml:lang="de">
      <author><personrefs to="eschbach"/></author>
      <title>Kelwitts Stern</title>
      <publisher>Bastei Lubbe</publisher>
      <year>1999</year>
      <month><jun/></month>
    </book>

    <inproceedings id="eschbach2000" xml:lang="de">
      <author><personrefs to="eschbach"/></author>
      <title><skippable>Der </skippable>Alptraummann</title>
      <booktitle>Destination 3001</booktitle>
      <editor><personrefs to="chambon silverberg"/></editor>
      <publisher>Tor</publisher>
      <year>2000</year>
    </inproceedings>

    <book id="eschbach2001" xml:lang="de">
      <author><personrefs to="eschbach"/></author>
      <title>Solar Station</title>
      <publisher>Bastei Lubbe</publisher>
      <year>2001</year>
      <month><jan/></month>
    </book>

    <book id="gibson1984" xml:lang="en">
      <author><personrefs to="gibson"/></author>
      <title>Neuromancer</title>
      <publisher>Victor Gollancz, Ltd.</publisher>
      <year>1984</year>
    </book>

    <book id="gibson1986" xml:lang="en">
      <author><personrefs to="gibson"/></author>
      <title>Burning Chrome and Other Stories</title>
      <publisher>Victor Gollancz, Ltd.</publisher>
      <year>1986</year>
      <note>
        <group xml:lang="fr">
          Titre de la traduction française :
          <emph emf="no" quotedf="yes">Gravé sur chrome</emph>
        </group>
        <group xml:lang="de">
          Titel der deutschen Übersetzung:
          <emph emf="no" quotedf="yes">Cyberspace</emph>
        </group>
      </note>
    </book>

    <book id="gibson1988" xml:lang="en">
      <author><personrefs to="gibson"/></author>
      <title>Mona Lisa Overdrive</title>
      <publisher>Victor Gollancz, Ltd.</publisher>
      <year>1988</year>
    </book>

    <book id="holbein1997" xml:lang="de">
      <editor><personrefs to="holbein"/></editor>
      <title>Dinoland</title>
      <publisher>Bastei Lubbe</publisher>
      <year>1997</year>
      <month><aug/></month>
    </book>

    <book id="honaker1991" xml:lang="fr">
      <author><personrefs to="honaker"/></author>
      <title>
        <foreigngroup xml:lang="en">Apocalypse Junction</foreigngroup>
      </title>
      <publisher>Fleuve Noir, no. 1810</publisher>
      <year>1991</year>
      <month><apr/></month>
      <number>8</number>
      <series>Le Commandeur</series>
    </book>

    <book id="king1978f" xml:lang="en">
      <author><personrefs to="king"/></author>
      <title>Night Shift</title>
      <publisher>Doubleday &amp; Co.</publisher>
      <year>1978</year>
      <note>
        <nonemptyinformation>
          <group xml:lang="en">Collection of 20 short stories</group>
          <group xml:lang="fr">Recueil de 20 nouvelles</group>
        </nonemptyinformation>
        <nonemptyinformation>
          <group xml:lang="en"/>
          <group xml:lang="fr">
            Titre de la traduction française : Danse macabre
          </group>
          <group xml:lang="de">
            Titel der deutschen Übersetzung: Nachtschicht
          </group>
        </nonemptyinformation>
      </note>
    </book>

    <book id="king1981i" xml:lang="en">
      <author><personrefs to="king"/></author>
      <title><foreigngroup xml:lang="fr">Danse macabre</foreigngroup></title>
      <publisher>Everest House</publisher>
      <year>1981</year>
      <month><jul/></month>
    </book>

    <book id="king1990" xml:lang="en">
      <author><personrefs to="king"/></author>
      <title><skippable>The </skippable>Stand</title>
      <publisher>Doubleday &amp; Co.</publisher>
      <year>1990</year>
      <address>New-York</address>
      <note>
        <nonemptyinformation>
          <group xml:lang="en">The Complete and Uncut Edition.</group>
          <group xml:lang="fr">Version intégrale.</group>
        </nonemptyinformation>
        <nonemptyinformation>
          <group xml:lang="en">Abridged version issued in 1978</group>
          <group xml:lang="fr">Version abrégée parue en 1978</group>
          <group xml:lang="de">
            Abgekürzte Auffassung im Jahre 1978 erschienen
          </group>
        </nonemptyinformation>
      </note>
    </book>

    <book id="king1998d" xml:lang="en">
      <author><personrefs to="king"/></author>
      <title>Bag of Bones</title>
      <publisher>
        <nonemptyinformation>
          <group xml:lang="en">Scribner Book Company</group>
          <group xml:lang="fr">Première édition américaine</group>
        </nonemptyinformation>
      </publisher>
      <year>1998</year>
      <month><sep/></month>
      <note>
        <nonemptyinformation>
          <group xml:lang="en">Translated into French and German</group>
          <group xml:lang="fr">
            Titre de la traduction française : Sac d'os
          </group>
          <group xml:lang="de">Titel der deutschen Übersetzung: Sara</group>
        </nonemptyinformation>
      </note>
    </book>

    <book id="lem1961" xml:lang="pl">
      <author><personrefs to="lem"/></author>
      <title>Solaris</title>
      <publisher>Wydawnictwo ministerwa Obrony Narodowej</publisher>
      <year>1961</year>
      <note><group xml:lang="fr">Traduit en français</group></note>
    </book>

    <book id="lem1968" xml:lang="pl">
      <author><personrefs to="lem"/></author>
      <title>Glos Pana</title>
      <publisher>Czytelnik</publisher>
      <year>1968</year>
      <address>
        <nonemptyinformation>
          <group xml:lang="pl">Warszawa</group>
          <group xml:lang="en">Warsaw</group>
          <group xml:lang="de">Warschau</group>
          <group xml:lang="fr">Varsovie</group>
        </nonemptyinformation>
      </address>
      <note>
        <group xml:lang="pl">
          Titre de la traduction française : 
          <emph quotedf="yes">La voix du maître</emph>
        </group>
      </note>
    </book>

    <book id="moorcock1971" xml:lang="en">
      <author><personrefs to="moorcock"/></author>
      <title><skippable>The </skippable>Sleeping Sorceress</title>
      <publisher>New En Library</publisher>
      <year>1971</year>
      <month><sep/></month>
      <note>
        <group xml:lang="en">
          Retitled <emph quotedf="yes">The Vanishing Tower</emph> in 1977
        </group>
        <group xml:lang="fr">
          Titre de la traduction française :
          <emph quotedf="yes">La sorcière dormante</emph>
        </group>
        <group xml:lang="de">
          Titel der deutschen Übersetzung:
          <emph quotedf="yes">Der verzauberte Turm</emph>
        </group>
      </note>
    </book>

    <book id="robeson1967" xml:lang="en">
      <author><personrefs to="robeson"/></author>
      <title>Murder Melody</title>
      <publisher>Bantam</publisher>
      <year>1967</year>
      <month><jan/></month>
      <number>15</number>
      <series>Doc Savage Series</series>
      <note>
        Originally published in <emph quotedf="yes">Doc Savage Magazine</emph>
        <group xml:lang="fr">
          Titre de la traduction française :
          <emph quotedf="yes">La mélodie de la mort</emph>
        </group>
        <group xml:lang="de">
          Titel der deutschen Übersetzung: 
          <emph quotedf="yes">Invasion aus der Tiefe</emph>
        </group>
      </note>
    </book>

    <book id="robeson1968i" xml:lang="en">
      <author><personrefs to="robeson"/></author>
      <title><skippable>The </skippable>Flaming Falcons</title>
      <publisher>Bantam</publisher>
      <year>1968</year>
      <month><nov/></month>
      <number>30</number>
      <series>Doc Savage Series</series>
      <note>
        <nonemptyinformation>
          <group xml:lang="fr">Première édition en juin 1939 dans</group>
          <group xml:lang="en">Originally published June 1939 in</group>
        </nonemptyinformation>
